source_id = {}
source_id['source_id'] = {}

key = 'CERES-EBAF-4-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA/LaRC'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF-4-0'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF4-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'ERA-40'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF - ERA-40 (European ReAnalysis 1957-2002)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2005'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-40'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-40'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'GPCP-2-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '2.3'

key = 'GPCP-1-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'ERA-INT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF-ERAINT 1.0 (2010): ECMWF - ERAINT (European ReAnalysis 1989-2010)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2010'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERAINT'
source_id['source_id'][key]['source_name'] = 'ECMWF-ERAINT'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va','zg']
source_id['source_id'][key]['source_version_number'] = 'N/A'

key = 'JRA25'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'JRA25 1.0 (2002): JRA25 (Japanese ReAnalysis 1957-2002)'
source_id['source_id'][key]['institution_id'] = 'MRI'
source_id['source_id'][key]['release_year'] = '2002'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'MRI-JRA25'
source_id['source_id'][key]['source_name'] = 'MRI-JRA25'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va','zg']
source_id['source_id'][key]['source_version_number'] = 'N/A'

key = 'TRMM-3B43v.7'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM (observation 2000-2009)'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'observation'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B43v.7'

key = 'RSS'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'REMSS-PRW 6.6.0 (2017): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'REMSS-PRW'
source_id['source_id'][key]['source_name'] = 'REMSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '6.6.0'

